server:
  port: 8080
spring:
  ##redis配置
  profiles: prod
  redis:
    database: 0
    host: 10.0.0.24
    port: 6379
    password:
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 0

  ## 数据库访问配置
  datasource:
    url: jdbc:mysql://rds03jhkvv73853nd232.mysql.rds.aliyuncs.com:3306
    username: xiaoshuidi
    password: ACA6VdyocBuTNduF
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

    ## 连接池配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 超时时间
    maxWait: 60000

    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000

    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false

    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20

    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000;config.decrypt=true;config.decrypt.key=${publicKey}
#短信配置
sms:
  baseUrl: http://xs1:5312
#基础信息配置
sso:
  host: http://narcissus.ih2ome.cn/sso
#云丁信息
yd:
  login:
    url: https://open.dding.net/public/oauth/index.html
  client_id: shuidiguanjia
  client_secret: b3a19f6ba2e99046582a9cb5de334de6
  smart_lock:
    permission_group: apartment_mg,lock_mg,pwd_op,ble_op,gateway_mg,gateway_op
    call_back:
          url: http://rose.ih2ome.cn/api/yunDing/callBack/setOAuthCode

